--CREATE TABLE IF NOT EXISTS RoleList (MemberID UNSIGNED BIGINT NOT NULL, GuildID UNSIGNED BIGINT NOT NULL, Role UNSIGNED BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS RoleList (MemberID BIGINT UNSIGNED NOT NULL, GuildID BIGINT UNSIGNED NOT NULL, Role BIGINT UNSIGNED NOT NULL, UNIQUE (MemberID, GuildID, Role));
--CREATE UNIQUE INDEX IF NOT EXISTS GuildUser on RoleList (MemberID, GuildID, Role);